# Generated by Django 5.0.4 on 2024-04-22 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speciality", models.CharField(max_length=100)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="icons")),
            ],
        ),
        migrations.CreateModel(
            name="DoctorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crm", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("cep", models.CharField(max_length=15)),
                ("street", models.CharField(max_length=100)),
                ("neighborhood", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("rg", models.ImageField(upload_to="rgs")),
                ("cim", models.ImageField(upload_to="cim")),
                ("picture", models.ImageField(upload_to="profile_pics")),
                ("description", models.TextField(blank=True, null=True)),
                ("bill", models.FloatField(default=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="doctor.speciality",
                    ),
                ),
            ],
        ),
    ]
