# Generated by Django 5.0.4 on 2024-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_opendate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opendate",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
